### ISSUE TITLE
When you set the Minute Tick Width to 0, the ticks get bigger instead of disappearing.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-world-clock#1]
What steps will reproduce the problem?
1. Add the World Clock Widget to a Presentation, set the clock to Analog, and the Minute Tick Width to 0 Pixels.
2. Notice when it plays on a Display, the Tick Width is not 0, and you can clearly see the Minute Ticks

For further clarification: http://www.screencast.com/t/3IG2HAztUrxI

What is the expected output? What do you see instead?
If the Width is set to 0, the Ticks should disappear.

**Comment by donnapep** [comment]
Fixed by https://github.com/Rise-Vision/widget-world-clock/pull/10

**Comment by donnapep** [comment]
@justinsmith1 Can you confirm that this was tested and that this issue can be closed? Thx.
