### ISSUE TITLE
Time Zone clocks don't populate

### ISSUE THREAD

**Issue by justinsmith1** [Rise-Vision/widget-world-clock#11]
When local time is not checked, no matter what time zone that is chosen, the digital clock remains 00:00:00 AM, and the analog clock has no hour, minute, or second hands.

http://screencast.com/t/1sF4qdgJe

http://screencast.com/t/9PuAQ7pBk

The widget should show the correct time for the chosen time zone if local time is not checked (for both the digital and analog clock).

**Comment by donnapep** [comment]
@justinsmith1 Can I get a sample Presentation to work with? Thx.

**Comment by justinsmith1** [comment]
@donnapep Sure thing. There is one in the Uptime company:

http://rva.risevision.com/#PRESENTATION_MANAGE/id=78d2e08d-abac-4b2a-902d-237e9a114541/company=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

**Comment by donnapep** [comment]
@justinsmith1 Can you clarify for me which Player it's not working on? I just tried preview and it works. Also, the Widget URLs should not start with `https`. Widget URLs should almost always be `http`. I would fix that as well and then retest. Thx.

**Comment by justinsmith1** [comment]
@donnapep it was not working on preview, nor any of our uptimes during the test. When I just checked this presentation, the 'use local time' was still checked. Upon unchecking, and selecting any time zone, the clock goes to 00:00:00AM.

As for http vs. https, I just copied those links right from the release notes doc.

**Comment by justinsmith1** [comment]
@donnapep just saw your comment on Trello. I will change them to http instead of https.

**Comment by justinsmith1** [comment]
@donnapep Issue still remains after changing to http. Can you replicate using the presentation that I linked now that 'use local time' is unchecked? I'm able to replicate in preview and on our uptimes.

**Comment by donnapep** [comment]
@justinsmith1 It looks like it's still using https? Where were the URLs updated? http://www.screencast.com/t/0s0hEwrUfTq

**Comment by justinsmith1** [comment]
@donnapep yep, the URLs were updated on both the test and production versions:

Test: http://screencast.com/t/IjIn2Ctw

Production: http://screencast.com/t/vNdbPrnNxQ

**Comment by donnapep** [comment]
@justinsmith1 You need to add the Widget again since it was added before the URLs were updated. Check the Presentation HTML to be sure that it's using `http` and not `https`, because right now it's using `https` and this is very likely the problem. Thx.

**Comment by justinsmith1** [comment]
@donnapep I tried removing the widget from the placeholder and re-adding but that still had https. I created a new presentation and added it there and it shows http. Looks to be working now. I will finish QA. Thanks!
